# Generated by Django 5.0.2 on 2024-03-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudoku", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boards",
            name="user",
            field=models.CharField(max_length=30),
        ),
    ]
