# Generated by Django 5.0.2 on 2024-03-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sudoku", "0002_alter_boards_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="token",
            new_name="email",
        ),
    ]
