# Generated by Django 5.0.2 on 2024-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudoku", "0003_rename_token_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="pwd",
            field=models.CharField(max_length=128),
        ),
    ]
