# Generated by Django 5.0.2 on 2024-04-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudoku", "0004_alter_users_pwd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boards",
            name="isFinished",
            field=models.FloatField(default=0.0),
        ),
    ]
