# Generated by Django 5.0.2 on 2024-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudoku", "0005_alter_boards_isfinished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boards",
            name="answer",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="boards",
            name="state",
            field=models.CharField(max_length=500),
        ),
    ]
